# Generated by Django 4.0.4 on 2022-04-29 12:12

from django.db import migrations

def capitalize(apps, schema_editor):
    Product = apps.get_model('main', 'Product')
    for product in Product.objects.all():
        product.name = product.name.capitalize()
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productimage_thumbnail'),
    ]

    operations = [
        migrations.RunPython(
            capitalize,
            migrations.RunPython.noop
        )
    ]

#above , Instead of using operations like CreateModel or AlterField, we are
#using a lower-level operation called RunPython, which takes a forward
#function and a backward function. In our case, we specify a noop backward
#function, which will allow us to go backward doing nothing instead of
#raising an exception.
#Once we apply this, all current products will have their name capitalized.
#It is important to realize that this migration will only be applied once.